apiVersion: v1
kind: Service
metadata:
  name: bloodflow-backend-service
spec:
  selector:
    app: bloodflow-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP